### PR TITLE
Corrections on controller.php file, to use the new intelmqctl interface

### PR DESCRIPTION
**Pull request by pedrosa-t**
Corrections on controller.php file, to use the new intelmqctl interface

### CODE REVIEW

**Comment by sebix** [comment]
Please update your intelmq-instance

**Comment by pedrosa-t** [comment]
I have the last intelmq version from the git (1.0.0dev4). And the intelmq-manager is also from git. 
I don't kwon if I have misconfigured something, but  monitor and management tabs I've error that I checked in the logs of apache and where related with the commands requested to execute against intelmqctl and saw that something had changed on intelmqctl.
After I changed some lines related with the construction of the commands, the errors where gone, I'm able to use monitor and management tabs and I can request botnet and bots to stop and/or start again.
I've canceled the previous merge request because on that I've only corrected bonet requestst. On my fork I thing I've resolved the problems related botnet and individual bot operations. The actions related to log I've also changed to the new intelmqctl syntax but I can't test them.

**Comment by sebix** [comment]
Depending on how you installed intelmq, did you upgrade both program also?

**Comment by pedrosa-t** [comment]
I've upgrade both. git pull for both. I're reruned the upgrade process of upgrade intelmq and seems ok. Thanks.

**Pull request closed without merging**
