### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by monoidic**
This PR:
* fixes an issue left over from #264, when editing path names, with `-queue` suffixes not being properly added/removed
* makes Mako use UTF-8 by default, hopefully fixing #266
* adds HTML escaping where possible, handling #267, #268, #269, and making `show_error` displaying formatted HTML opt-in

### CODE REVIEW

**Comment by ghost** [comment]
Wow, that was fast :flushed: 

#266 (introduced by myself) seems to be fixed

CodeQL reports
> Fixed alerts
>
>    Incomplete string escaping or encoding (intelmq_manager/static/js/monitor.js#L547)
    Client-side cross-site scripting (intelmq_manager/static/js/monitor.js#L291)
    Client-side cross-site scripting (intelmq_manager/static/js/monitor.js#L314)

**Comment by ghost** [comment]
@e3rd Could you have a look please?

**Comment by monoidic** [comment]
Got a couple of other things lined up I'll tack onto this PR next week, actually.

**Review by e3rd — APPROVED** [review]
Seems good to me, good work!

**Review by ghost — APPROVED** [review]
Thanks a lot for updating the code to make it easier to read, that's an important improvement!

Code LGTM

**Comment by ghost** [comment]
Many thanks also from my side for all your hard work! We really appreciate that.

**Pull request merged**
