### PR TITLE
Implement user accounts and token based authentication with CSRF protection

### PR DESCRIPTION
**Pull request by bernhard-herzog**
Implement user accounts and token based authentication

This pull request adds a store for user accounts and session data and
implements sessions on top of that as outlined in the discussion for
#111.

The UI part is a bit unpolished in the current version, but it's working
and can at least serve as a starting point for discussing how to merge
this.

### CODE REVIEW

**Comment by bernhardreiter** [comment]
Some tasks left:
 * enable running the tests
 * enable running the type checks
 * document how to add and remove users
 * improve frontend for better handling if not-logged in (bring up login-dialog)
 * Do some more testing in error cases

**Comment by wagner-certat** [comment]
That looks like lots of efforts have been made to accomplish this! Many thanks!

Is this intended to get merged or is it WIP?

**Comment by bernhardreiter** [comment]
> Is this intended to get merged or is it WIP?

Both! ;)

Because there are some things which would be better, and it is likely that we'll improve them. On the other hand, it already improves an important security property, so it is a lot better than before and should see production as soon as possible.

**Comment by bernhardreiter** [comment]
Thanks @wagner-certat

**Pull request merged**
