### PR TITLE
full 14 hours work

### LINKED ISSUE #143: Show status of bots and queues in config network
Needs to be defined, has been requested multiple times.

### LINKED ISSUE #146: Button to copy/duplicate bots

### PR DESCRIPTION
**Pull request by e3rd**
intelmqctl-run integration, live queues in network, better error reporting, usability fixes, see changelog

Fixes #143 
Fixes #146 

I know there is a lot of changes, so this is just an invitation to the discussino. **BEFORE MERGING** few things need to be repaired in inspect panel at line `monitor.js:383`:
* [x]  may be a huge security flaw, sanitize `msg` and everything...
* [x] try to disturb message sending by an apostrophe `'`
* [x] queue displaying in network seem to have forgotten internal queue

### CODE REVIEW

**Comment by wagner-certat** [comment]
Wow! I'll need some time to try all that next week :)

**Review by ghost — CHANGES_REQUESTED** [review]
Very cool changes!

In the monitor page the Inspect element is shown although no bot is selected/defined (resulting in an error when used).

The black error-box in the top right corner is can't be hidden/closed. Probably a simple "Close" link at the end of the (expanded) box to hide it?

**Comment by e3rd** [comment]
Many new features that should've been added before. When I was debugging something I really needed those, see the changelog (or recent commit message).

>  Inspect element is shown 
should be handled, now the behaviour is the same as for logs-panel

> black error-box
If not resized manually, click toggled expansion, double clicke closed the box. But I agree a button missed.

Dependent on the groups from https://github.com/certtools/intelmq/pull/1227

**Comment by wagner-certat** [comment]
> > black error-box

> If not resized manually, click toggled expansion, double clicke closed the box. But I agree a button missed.

Or as hover show something like "Click to expand. Double-Click to close.".

FYI: I intend to do a 1.0.0 release before merging this. Then the compatible versions will be aligned, as this PR needs intelmq >= 1.1.0

**Comment by e3rd** [comment]
Hover title added.  
Okay, looking forward to the merge :)

**Pull request merged**
