### PR TITLE
Fix edges, sane default bot IDs

### PR DESCRIPTION
**Pull request by monoidic**
This PR fixes a current issue where working with edges between bots is broken, due to added edges not being transmitted to the server with the new API. Along that, it fixes an UX issue, with the `destination_queues` parameter being visible in the bot editor.
It also fixes issue #263, restoring the sane default bot IDs.

### CODE REVIEW

**Comment by monoidic** [comment]
Actually, rather than working with `app.edges`, I think it'd be a better idea to get rid of it entirely and merge the edges into the bots here as well. It'll make something else I'm working on (fixing bot renaming issues) simpler as well.

**Comment by monoidic** [comment]
Just noticed that the variable `node` declared on line 586 in `configs.js` is actually meant to be a global variable (not just declared as such due to the wonderful defaults of JS).

**Comment by monoidic** [comment]
There's still quite a few rough edges here, I'll work on them for a bit.

**Comment by ghost** [comment]
> There's still quite a few rough edges here, I'll work on them for a bit.

I feel your pain. Thanks for tackling this issue!

**Comment by monoidic** [comment]
I think I managed to remove the bugs I'd introduced now.

* `pipeline.js` is redundant due to the changes and was removed
* `ALLOWED_PATH` and `CONTROLLER_CMD` are defined in a seperate .js file rather than being templated into the HTML, fixing #183
* edge IDs are now `${source_node}|${destination_node}|${edge_name}`
  *  some loops which previously iterated over every single edge should be a bit faster now
* A quick fix was done on the race condition from trying to call both the `/runtime` and `/positions` API endpoints at the same time, when `/runtime` is updating `runtime.yaml` at the same time that `/positions` is trying to parse it
  * this should probably be fixed in the backend with e.g a lockfile on `runtime.yaml`
* various tweaks, like reducing the scope of variables and using string templates instead of string concatenation

**Review by e3rd — APPROVED** [review]
I appreciate the fresh JS syntax, great work!

**Comment by ghost** [comment]
Thank you very much!

I picked the commits for the maintenance branch and applied some minor (administrative) additions in 83f999c and 92f726a.

We need to have a look at some potential security-related issues, for which I'll open separate issues.

**Pull request merged**
