### PR TITLE
Update config.php

### PR DESCRIPTION
**Pull request by einar-lanfranco**
Hello, the previous fix doesnt work, because json_decode from proc got a array of arrays in ['paths'] and FILES keep empty.
I map the array to a dict and now it works, please let me know what you think.

Regards

### CODE REVIEW

**Comment by wagner-certat** [comment]
Argh, looks like I completely messed it up last time. I had it working already but must had confound something later. Embarassing

**Comment by wagner-certat** [comment]
Which IntelMQ version do you use and what is the exact problem you experience?

**Comment by einar-lanfranco** [comment]
> Argh, looks like I completely messed it up last time. I had it working already but must had confound something later. Embarassing

Hahaha, its always happens to me! Thanks for the great job you do. 

> Which IntelMQ version do you use and what is the exact problem you experience?

You need i to answer this question? From the previous answer i understand it is not necesary, but just in case, 2.2.1 and the problem is empty FILES  array.

**Comment by wagner-certat** [comment]
> > Which IntelMQ version do you use and what is the exact problem you experience?
> 
> You need i to answer this question? From the previous answer i understand it is not necesary, but just in case, 2.2.1 and the problem is empty FILES array.

I cannot reproduce the issue. For example I modified the file paths to have a `2` appended:
```bash
intelmq@medan:/opt/intelmq/etc> intelmqctl -t json debug --get-paths
{"paths": {"BOTS_FILE": "/opt/intelmq/etc/BOTS2", "DEFAULTS_CONF_FILE": "/opt/intelmq/etc/defaults.conf2", "HARMONIZATION_CONF_FILE": "/opt/intelmq/etc/harmonization.conf2", "PIPELINE_CONF_FILE": "/opt/intelmq/etc/pipeline.conf2", "RUNTIME_CONF_FILE": "/opt/intelmq/etc/runtime.conf2", "VAR_RUN_PATH": "/opt/intelmq/var/run/", "STATE_FILE_PATH": "/opt/intelmq/var/lib/state.json", "DEFAULT_LOGGING_PATH": "/opt/intelmq/var/log/", "__file__": "/home/sebastianw/dev/intelmq/intelmq/bin/intelmqctl.py", "CONFIG_DIR": "/opt/intelmq/etc/", "ROOT_DIR": "/opt/intelmq/"}}
```
The about page shows them:
image

And `$FILES` looks like:
```php
array(6) {
  ["bots"]=>
  string(22) "/opt/intelmq/etc/BOTS2"
  ["defaults"]=>
  string(31) "/opt/intelmq/etc/defaults.conf2"
  ["harmonization"]=>
  string(36) "/opt/intelmq/etc/harmonization.conf2"
  ["pipeline"]=>
  string(31) "/opt/intelmq/etc/pipeline.conf2"
  ["runtime"]=>
  string(30) "/opt/intelmq/etc/runtime.conf2"
  ["positions"]=>
  string(40) "/opt/intelmq/etc//manager/positions.conf"
}
```
And in the configuration tab, the modified files are loaded.

I'm using the master branches each.

**Comment by wagner-certat** [comment]
Can you please show `intelmqctl --version`, `intelmqctl check` and `intelmqctl -t json debug`?

**Comment by einar-lanfranco** [comment]
root@fd4bed7448a6:/# intelmqctl --version
2.2.0
root@fd4bed7448a6:/# intelmqctl check
Reading configuration files.
Checking defaults configuration.
Checking runtime configuration.
Checking runtime and pipeline configuration.
Checking harmonization configuration.
Checking for bots.
No issues found.
root@fd4bed7448a6:/# intelmqctl -t json debug
{"paths": [["BOTS_FILE", "/opt/intelmq/etc/BOTS"], ["DEFAULTS_CONF_FILE", "/opt/intelmq/etc/defaults.conf"], ["HARMONIZATION_CONF_FILE", "/opt/intelmq/etc/harmonization.conf"], ["PIPELINE_CONF_FILE", "/opt/intelmq/etc/pipeline.conf"], ["RUNTIME_CONF_FILE", "/opt/intelmq/etc/runtime.conf"], ["VAR_RUN_PATH", "/opt/intelmq/var/run/"], ["STATE_FILE_PATH", "/opt/intelmq/var/lib/state.json"], ["DEFAULT_LOGGING_PATH", "/opt/intelmq/var/log/"], ["__file__", "/opt/dev_intelmq/intelmq/bin/intelmqctl.py"], ["CONFIG_DIR", "/opt/intelmq/etc/"], ["ROOT_DIR", "/opt/intelmq/"]], "environment_variables": [["INTELMQ_ROOT_DIR", null], ["INTELMQ_PATHS_NO_OPT", null], ["INTELMQ_PATHS_OPT", null], ["INTELMQ_MANAGER_CONTROLLER_CMD", null]]}

**Comment by einar-lanfranco** [comment]
root@fd4bed7448a6:/# cat pepe.php 
<?php 
$auxiliar='{"paths": [["BOTS_FILE", "/opt/intelmq/etc/BOTS"], ["DEFAULTS_CONF_FILE", "/opt/intelmq/etc/defaults.conf"], ["HARMONIZATION_CONF_FILE", "/opt/intelmq/etc/harmonization.conf"], ["PIPELINE_CONF_FILE", "/opt/intelmq/etc/pipeline.conf"], ["RUNTIME_CONF_FILE", "/opt/intelmq/etc/runtime.conf"], ["VAR_RUN_PATH", "/opt/intelmq/var/run/"], ["STATE_FILE_PATH", "/opt/intelmq/var/lib/state.json"], ["DEFAULT_LOGGING_PATH", "/opt/intelmq/var/log/"], ["__file__", "/opt/dev_intelmq/intelmq/bin/intelmqctl.py"], ["CONFIG_DIR", "/opt/intelmq/etc/"], ["ROOT_DIR", "/opt/intelmq/"]], "environment_variables": [["INTELMQ_ROOT_DIR", null], ["INTELMQ_PATHS_NO_OPT", null], ["INTELMQ_PATHS_OPT", null], ["INTELMQ_MANAGER_CONTROLLER_CMD", null]]}';
print_r(json_decode($auxiliar));
?>

root@fd4bed7448a6:/# php pepe.php 
stdClass Object
(
    [paths] => Array
        (
            [0] => Array
                (
                    [0] => BOTS_FILE
                    [1] => /opt/intelmq/etc/BOTS
                )

            [1] => Array
                (
                    [0] => DEFAULTS_CONF_FILE
                    [1] => /opt/intelmq/etc/defaults.conf
                )

            [2] => Array
                (
                    [0] => HARMONIZATION_CONF_FILE
                    [1] => /opt/intelmq/etc/harmonization.conf
                )

            [3] => Array
                (
                    [0] => PIPELINE_CONF_FILE
                    [1] => /opt/intelmq/etc/pipeline.conf
                )

            [4] => Array
                (
                    [0] => RUNTIME_CONF_FILE
                    [1] => /opt/intelmq/etc/runtime.conf
                )

            [5] => Array
                (
                    [0] => VAR_RUN_PATH
                    [1] => /opt/intelmq/var/run/
                )

            [6] => Array
                (
                    [0] => STATE_FILE_PATH
                    [1] => /opt/intelmq/var/lib/state.json
                )

            [7] => Array
                (
                    [0] => DEFAULT_LOGGING_PATH
                    [1] => /opt/intelmq/var/log/
                )

            [8] => Array
                (
                    [0] => __file__
                    [1] => /opt/dev_intelmq/intelmq/bin/intelmqctl.py
                )

            [9] => Array
                (
                    [0] => CONFIG_DIR
                    [1] => /opt/intelmq/etc/
                )

            [10] => Array
                (
                    [0] => ROOT_DIR
                    [1] => /opt/intelmq/
                )

        )

    [environment_variables] => Array
        (
            [0] => Array
                (
                    [0] => INTELMQ_ROOT_DIR
                    [1] => 
                )

            [1] => Array
                (
                    [0] => INTELMQ_PATHS_NO_OPT
                    [1] => 
                )

            [2] => Array
                (
                    [0] => INTELMQ_PATHS_OPT
                    [1] => 
                )

            [3] => Array
                (
                    [0] => INTELMQ_MANAGER_CONTROLLER_CMD
                    [1] => 
                )

        )

)

**Comment by wagner-certat** [comment]
Please upgrade IntelMQ to version 2.2.1

**Comment by einar-lanfranco** [comment]
Sorry for the delay, busy weeks, you are correct!

The new version (2.2.1) changes the output:

intelmqctl -t json debug
{"paths": {"BOTS_FILE": "/opt/intelmq/etc/BOTS", "DEFAULTS_CONF_FILE": "/opt/intelmq/etc/defaults.conf", "HARMONIZATION_CONF_FILE": "/opt/intelmq/etc/harmonization.conf", "PIPELINE_CONF_FILE": "/opt/intelmq/etc/pipeline.conf", "RUNTIME_CONF_FILE": "/opt/intelmq/etc/runtime.conf", "VAR_RUN_PATH": "/opt/intelmq/var/run/", "STATE_FILE_PATH": "/opt/intelmq/var/lib/state.json", "DEFAULT_LOGGING_PATH": "/opt/intelmq/var/log/", "__file__": "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", "CONFIG_DIR": "/opt/intelmq/etc/", "ROOT_DIR": "/opt/intelmq/"}, "environment_variables": {"INTELMQ_ROOT_DIR": null, "INTELMQ_PATHS_NO_OPT": null, "INTELMQ_PATHS_OPT": null, "INTELMQ_MANAGER_CONTROLLER_CMD": null, "PATH": "/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}}

Dismiss my patch beacuse it doesnt work for intelmq 2.2.1, only for previous versions.

**Pull request closed without merging**
